networks:
  backend: {}
  frontend: {}
services:
  todo-api:
    build:
      context: ./src/api
    deploy:
      replicas: 1
    image: brbarnett/todo-api:ci
    environment:
      - PORT=80
    networks:
      backend: null
      frontend: null
  todo-ingress:
    build:
      context: ./src/ingress
    deploy:
      replicas: 2
    image: brbarnett/todo-ingress:ci
    networks:
      frontend: null
    ports:
    - published: 80
      target: 80
  todo-web:
    build:
      context: ./src/web
    deploy:
      replicas: 3
    image: brbarnett/todo-web:ci
    networks:
      frontend: null
version: '3.6'

