version: '3.6'

services:
  
  todo-bff:
    image: brbarnett/todo-bff
    build:
      context: todo-bff
    networks:
      - frontend
    ports:
      - "80:80"
    deploy:
      replicas: 2

  todo-web:
    image: brbarnett/todo-web
    build:
      context: todo-web
    networks:
      - frontend
    deploy:
      replicas: 3
  
  todo-api:
    image: brbarnett/todo-api
    build:
      context: todo-api
    networks:
      - frontend
      - backend
    environment:
      - PORT=80
    deploy:
      replicas: 1

  #todos:

  # visualizer:
  #   image: dockersamples/visualizer
  #   ports:
  #     - 8084:8080
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock

networks:
  frontend:
  backend: