version: '3.6'

services:
  
  todo-web:
    image: brbarnett/todo-web:latest
    build:
      context: todo-web
    networks:
      - frontend
  
  todo-api:
    image: brbarnett/todo-api:latest
    build:
      context: todo-api
    networks:
      - frontend
      - backend

  #todos:

networks:
  frontend:
  backend: