version: '3.6'

services:
  
  todo-ingress:
    image: brbarnett/todo-ingress
    build:
      context: ./src/ingress
    networks:
      - frontend
    ports:
      - "80:80"
    deploy:
      replicas: 2

  todo-web:
    image: brbarnett/todo-web
    build:
      context: ./src/web
    networks:
      - frontend
    deploy:
      replicas: 3
  
  todo-api:
    image: brbarnett/todo-api
    build:
      context: ./src/api
    networks:
      - frontend
      - backend
    environment:
      - PORT=80
    deploy:
      replicas: 1

networks:
  frontend:
  backend: