version: '3.6'

services:
  
  todo-bff:
    ports:
      - "80:80"
    deploy:
      replicas: 2

  todo-web:
    deploy:
      replicas: 3

  todo-api:
    environment:
      - PORT=80
    deploy:
      replicas: 1
