networks:
  backend: {}
  frontend: {}
services:
  todo-api:
    build:
      context: todo-api
    deploy:
      replicas: 1
    image: brbarnett/todo-api
    environment:
      - PORT=80
    networks:
      backend: null
      frontend: null
  todo-bff:
    build:
      context: todo-bff
    deploy:
      replicas: 2
    image: brbarnett/todo-bff
    networks:
      frontend: null
    ports:
    - published: 80
      target: 80
  todo-web:
    build:
      context: todo-web
    deploy:
      replicas: 3
    image: brbarnett/todo-web
    networks:
      frontend: null
version: '3.6'

