apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: test-todo-aks-cluster-com
  namespace: default
spec:
  secretName: test-todo-aks-cluster-com-tls
  issuerRef:
    name: letsencrypt-staging
  commonName: todo-aks-cluster.centralus.cloudapp.azure.com
  dnsNames:
  - todo-aks-cluster.centralus.cloudapp.azure.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - todo-aks-cluster.centralus.cloudapp.azure.com