apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: todo-aks-cluster-domain
  namespace: default
spec:
  secretName: todo-aks-cluster-domain-tls
  issuerRef:
    name: letsencrypt
  commonName: todo-aks-cluster.centralus.cloudapp.azure.com
  dnsNames:
  - todo-aks-cluster.centralus.cloudapp.azure.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - todo-aks-cluster.centralus.cloudapp.azure.com