apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt-staging
  namespace: default
spec:
  acme:
    server: https://acme-staging.api.letsencrypt.org/directory
    email: bbarnett@rightpoint.com
    privateKeySecretRef:
      name: letsencrypt-staging
    http01: {}