dependencies:
  - name: nginx-ingress
    version: ~0.19.2
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: cert-manager
    version: ~0.2.10
    repository: https://kubernetes-charts.storage.googleapis.com