api:
  image: brbarnett/todo-api:ci
  name: todo-api
  replicas: 1

web:
  image: brbarnett/todo-web:ci
  name: todo-web
  replicas: 6

ingress:
  host: todo-aks-cluster.centralus.cloudapp.azure.com
  name: todo-ingress
  secret: todo-aks-cluster-com-tls

issuer:
  email: bbarnett@rightpoint.com