api:
  image: brbarnett/todo-api:ci
  name: todo-api
  replicas: 1

web:
  image: brbarnett/todo-web:ci
  name: todo-web
  replicas: 4

ingress:
  host: todo-aks-cluster.centralus.cloudapp.azure.com
  name: todo-ingress
  secret: todo-aks-cluster-com-tls

issuer:
  email: bbarnett@rightpoint.com

nginx-ingress:
  controller:
    service:
      # Azure public, static IP address
      loadBalancerIP: 104.43.217.79
  rbac:
    # Not supported in Azure
    create: false

cert-manager:
  # crd-install hook to ensure this runs prior to other resources. CRD thing
  issuerAnnotations:
    "helm.sh/hook": "crd-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  rbac:
    # Not supported in Azure
    create: false
  extraArgs:
    # Required to use Issuer instead of default ClusterIssuer
    - '{--default-issuer-name=letsencrypt-prod,--default-issuer-kind=Issuer}'