apiVersion: v1
kind: Service
metadata:
  name: todo-api
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: todo-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api
spec:
  selector:
    matchLabels:
      app: todo-api
  replicas: 1
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      containers:
      - name: todo-api
        image: brbarnett/todo-api:ci
        env:
        - name: PORT
          value: "80"
        ports:
        - containerPort: 80