apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.api.name }}
labels:
  heritage: {{ .Release.Service }}
  release: {{ .Release.Name }}
  chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.api.name }}
  replicas: {{ .Values.api.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.api.name }}
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    spec:
      containers:
      - name: {{ .Values.api.name }}
        image: {{ .Values.api.image }}
        env:
        - name: PORT
          value: "80"
        ports:
        - containerPort: 80