apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: default
spec:
  acme:
    server: https://acme-v01.api.letsencrypt.org/directory
    email: {{ .Values.issuer.email }}
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}